version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: mnovikov-redis
    restart: always
    env_file:
      - .env
    volumes:
      - cache-volume:/data
    expose:
      - "6379"
  celery:
    build: .
    command: celery -A src.worker.celery worker --loglevel=info
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/1 flower --port=5555
    ports:
      - "5556:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - celery
volumes:
  cache-volume: { }
